
name: Markdown Lint Check

on:
  pull_request_target:
    branches:
    - main
    paths:
    - '**.md'
    - '!.github/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: npm install -g markdownlint-cli
    - name: Run linter
      run: markdownlint . --ignore node_modules --ignore .github
